# Generated by Django 5.2.4 on 2025-09-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
